# test data load / format
import sys



def load_data(schedule):
    schedule = [['known_issues_qa', 'Yes', 'Set of tests failing (from low-priority issues) in QA'],
                ['known_issues_semi', 'Yes', 'Set of tests failing (from low-priority issues) in SEMI'],
                ['api_basic_qa', 'Yes', 'Basic set of external-API tests in QA'],
                ['api_basic_semi', 'Yes', 'Basic set of external-API tests in SEMI'],
                ['api_risk_basic_qa', 'Yes', 'Basic set of external-API risk tests in QA'],
                ['api_risk_basic_semi', 'Yes', 'Basic set of external-API risk tests in SEMI'],
                ['CAPTCHA_QA', 'Yes', 'Full set of CAPTCHA tests in QA'],
                ['peg_basic_qa', 'Yes', 'Basic set of PeG tests in QA'],
                ['peg_basic_semi', 'Yes', 'Basic set of PeG tests in SEMI'],
                ['data_basic_qa', 'Yes', 'Test data (e.g. gestalt) source in QA'],
                ['data_basic_semi', 'Yes', 'Test data (e.g. gestalt) source in SEMI'],
                ['plastic_basic_qa', 'Yes', 'Basic set of plastic tests across multiple products in QA'],
                ['plastic_basic_semi', 'Yes', 'Basic set of plastic tests across multiple products in SEMI'],
                ['capi_basic_qa', 'Yes', 'Basic set of CAPI tests in QA'],
                ['capi_basic_semi', 'Yes', 'Basic set of CAPI tests in SEMI'],
                ['capi_features_qa', 'Yes', 'CAPI features tests in QA'],
                ['capi_features_semi', 'Yes', 'CAPI features tests in SEMI'],
                ['mapi_basic_qa', 'Yes', 'Basic set of CAPI Mall tests in QA'],
                ['mapi_basic_semi', 'No', 'Basic set of Mall tests in SEMI'],
                ['promo_basic_qa', 'Yes', 'Basic set of CAPI tests in QA'],
                ['promo_basic_semi', 'Yes', 'Basic set of CAPI tests in SEMI'],
                ['program_basic_qa', 'Yes', 'Basic set of CAPI tests in QA'],
                ['program_basic_semi', 'Yes', 'Basic set of CAPI tests in SEMI'],
                ['assist_basic_qa', 'Yes', 'Basic set of assist tests in QA'],
                ['assist_basic_semi', 'Yes', 'Basic set of assist tests in SEMI'],
                ['biz_basic_qa', 'Yes', 'Basic set of biz/bulk tests in QA'],
                ['biz_basic_semi', 'Yes', 'Basic set of biz/bulk tests in SEMI'],
                ['storefront_basic_qa', 'Yes', 'Basic set of Storefront tests in QA'],
                ['storefront_basic_semi', 'Yes', 'Basic set of Storefront tests in SEMI'],
                ['storefront_variants_qa', 'Yes', 'Variants (i.e. multi-item buys) set of tests for Storefront in QA'],
                ['storefront_variants_semi', 'Yes',
                 'Variants (i.e. multi-item buys) set of tests for Storefront in SEMI'],
                ['storefront_i18n_qa', 'Yes', 'I18N (i.e. Internationalization)  set of tests for Storefront in SEMI'],
                ['storefront_i18n_semi', 'Yes',
                 'I18N (i.e. internationalization)  set of tests for Storefront in SEMI'],
                ['storefront_regressions_qa', 'Yes',
                 'Large set of buys across buy_types, currencies and credit cards in QA'],
                ['storefront_regressions_semi', 'Yes',
                 'Large set of buys across buy_types, currencies and credit cards in SEMI'],
                ['storefront_promo_qa', 'Yes', 'Basic set of Storefront promo-tests in QA'],
                ['storefront_promo_semi', 'Yes', 'Basic set of Storefront promo-tests in SEMI'],
                ['clientconfig_basic_qa', 'Yes', 'Full set of clientconfig tests in QA'],
                ['clientconfig_basic_semi', 'Yes', 'Full set of clientconfig tests in SEMI'],
                ['econsumer_basic_qa', 'Yes', 'Basic set of eConsumer tests in QA'],
                ['econsumer_basic_semi', 'Yes', 'Basic set of eConsumer tests in QA'],
                ['mallfront_basic_qa', 'Yes', 'Basic set of MallFront tests in QA'],
                ['mallfront_basic_semi', 'No', 'Basic set of MallFront tests in QA'],
                ['FINCEN_QA', 'Yes', 'FINCEN daily limit'], ['FINCEN_SEMI', 'Yes', 'FINCEN daily limit'],
                ['PAYMENT', 'Yes', 'Buy cards using a variety of products and services.'],
                ['PROCESSORS', 'Yes', 'Test a variety of processors.'],
                ['paypal_basic_qa', 'Yes', 'Basic set of PayPal tests in QA'],
                ['paypal_basic_semi', 'Yes', 'Basic set of PayPal tests in SEMI'],
                ['redeem_basic_qa', 'Yes', 'Basic set of redemption tests in QA'],
                ['redeem_basic_semi', 'Yes', 'Basic set of redemption tests in SEMI'],
                ['SS2_QA', 'Yes', 'Basic set of selfservice tests in QA'],
                ['xreport', 'Yes', 'Generate and email composite report.'],
                ['TASKS', 'Yes', 'Run any existing tasks stored in tasks table.'],
                ['NOP', 'Yes', 'A NOP job - no tests are run.'], ['SMOKE_QA', 'Yes', 'Smoke-tests for QA'],
                ['SMOKE_SEMI', 'Yes', 'Smoke-tests for SEMI'],
                ['T_RELEASE_PAGES', 'Yes', 'Trial tests for Release Pages.'],
                ['T_QUICKCHECK_DD', 'Yes', 'Trial tests for quickcheck on desktop/digital'],
                ['T_QUICKCHECK_MD', 'Yes', 'Trial quickcheck tests on desktop/digital'],
                ['T_QUICKCHECK_DP', 'Yes', 'Trial quickcheck tests on desktop/plastic'],
                ['T_QUICKCHECK_MP', 'Yes', 'Trial quickcheck tests on mobile/plastic'],
                ['T_QUICKCHECK_S', 'Yes', 'Trial quickcheck tests for Storefront digital'],
                ['RELEASE_PAGES', 'No', 'Base tests for Release Pages.'],
                ['QUICKCHECK_DD', 'No', 'Base tests on quickcheck for desktop/digital'],
                ['QUICKCHECK_MD', 'No', 'Base tests on quickcheck for mobile/digital'],
                ['QUICKCHECK_DP', 'No', 'Base tests on quickcheck for desktop/plastic'],
                ['QUICKCHECK_MP', 'No', 'Base tests on quickcheck for mobile/plastic'],
                ['QUICKCHECK_S', 'No', 'Base quickcheck tests for Storefront digital'],
                ['RELEASE_DAY_TESTS', 'No', 'Base tests for Release Pages.'],
                ['storefront_basic_qa_multibrowser', 'Yes',
                 'Basic set of Storefront tests in QA across multiple browsers'],
                ['storefront_basic_semi_multibrowser', 'Yes',
                 'Basic set of Storefront tests in SEMI across multiple browsers'],
                ['storefront_variants_qa_multibrowser', 'Yes',
                 'Variant set (i.e. multi-item buys) of Storefront tests, multiple browsers, in QA'],
                ['storefront_variants_semi_multibrowser', 'Yes',
                 'Variant set (i.e. multi-item buys) of Storefront tests, multiple browsers, in SEMI'],
                ['storefront_i18n_qa_multibrowser', 'Yes',
                 'Set of I18N (i.e. internationalization) Storefront tests, multiple browsers, in QA'],
                ['storefront_i18n_semi_multibrowser', 'Yes',
                 'Set of I18N (i.e. internationalization) Storefront tests in SEMI'],
                ['peg_basic_semi_multibrowser_desktop', 'Yes',
                 'Full set of PeG tests in SEMI, across multiple browsers on unmanaged brands'],
                ['peg_basic_semi_multibrowser_mobile', 'Yes',
                 'Full set of PeG tests in SEMI, across multiple browsers'],
                ['peg_basic_qa_multibrowser_desktop', 'Yes', 'Full set of PeG tests in QA, across multiple browsers'],
                ['peg_basic_qa_multibrowser_mobile', 'Yes', 'Full set of PeG tests in QA, across multiple browsers'],
                ['API_SEMI', 'Yes', 'Full set of External API tests in SEMI'],
                ['PEG_SEMI', 'Yes', 'Full set of PeG tests in SEMI'], ['PEG_QA', 'Yes', 'Full set of PeG tests in QA'],
                ['CAPI_SEMI', 'Yes', 'Full set of CAPI v3 tests in SEMI'],
                ['CAPIV4_SEMI', 'Yes', 'Full set of CAPI v4 tests in SEMI'],
                ['CAPI_PEG_SEMI', 'Yes', 'Full set of CAPI/PEG tests in SEMI'],
                ['ASSIST_SEMI', 'Yes', 'Full set of assist tests in SEMI'],
                ['BIZ_PARTIAL_SEMI', 'Yes', 'Large set of biz/bulk tests in SEMI'],
                ['BIZ_VARIANTS', 'Yes', 'Variant set of biz/bulk tests'],
                ['STOREFRONT_SEMI', 'Yes', 'Full set of storefront tests in SEMI'],
                ['CSMR_PARTIAL_SEMI', 'Yes', 'Full set of consumer tests in SEMI'],
                ['CSMR_VARIANTS', 'Yes', 'Variant set of consumer tests']]
    schedule_plus = [['API_SEMI', 'Yes', '5    10      *     *      7     *', 'Full set of External API tests in SEMI'],
                     ['ASSIST_SEMI', 'Yes', '5   10     *     *      7     *', 'Full set of assist tests in SEMI'],
                     ['BIZ_PARTIAL_SEMI', 'Yes', '5   10     *     *      7     *',
                      'Large set of biz/bulk tests in SEMI'],
                     ['BIZ_VARIANTS', 'Yes', '5   10   *     *      7     *', 'Variant set of biz/bulk tests'],
                     ['CAPIV4_SEMI', 'Yes', '5    10      *     *      7     *', 'Full set of CAPI v4 tests in SEMI'],
                     ['CAPI_PEG_SEMI', 'Yes', '5    10      *     *      7     *',
                      'Full set of CAPI/PEG tests in SEMI'],
                     ['CAPI_SEMI', 'Yes', '5    10      *     *      7     *', 'Full set of CAPI v3 tests in SEMI'],
                     ['CAPTCHA_QA', 'Yes', '5    0      *     *      *     *', 'Full set of CAPTCHA tests in QA'],
                     ['CSMR_PARTIAL_SEMI', 'Yes', '5   11   *     *      7     *',
                      'Full set of consumer tests in SEMI'],
                     ['CSMR_VARIANTS', 'Yes', '5   11   *     *      7     *', 'Variant set of consumer tests'],
                     ['FINCEN_QA', 'Yes', '5   5   *     *      3,7     *', 'FINCEN daily limit'],
                     ['FINCEN_SEMI', 'Yes', '5   5   *     *      2,6     *', 'FINCEN daily limit'],
                     ['NOP', 'Yes', '5    9      *    *       *     *', 'A NOP job - no tests are run.'],
                     ['PAYMENT', 'Yes', '5   5   *     *      3,7     *',
                      'Buy cards using a variety of products and services.'],
                     ['PEG_QA', 'Yes', '5    10      *     *      7     *', 'Full set of PeG tests in QA'],
                     ['PEG_SEMI', 'Yes', '5    10      *     *      7     *', 'Full set of PeG tests in SEMI'],
                     ['PROCESSORS', 'Yes', '5   5   *     *      1     *', 'Test a variety of processors.'],
                     ['QUICKCHECK_DD', 'No', '* * * 1 * *', 'Base tests on quickcheck for desktop/digital'],
                     ['QUICKCHECK_DP', 'No', '* * * 1 * *', 'Base tests on quickcheck for desktop/plastic'],
                     ['QUICKCHECK_MD', 'No', '* * * 1 * *', 'Base tests on quickcheck for mobile/digital'],
                     ['QUICKCHECK_MP', 'No', '* * * 1 * *', 'Base tests on quickcheck for mobile/plastic'],
                     ['QUICKCHECK_S', 'No', '* * * 1 * *', 'Base quickcheck tests for Storefront digital'],
                     ['RELEASE_DAY_TESTS', 'No', '* * * 1 * *', 'Base tests for Release Pages.'],
                     ['RELEASE_PAGES', 'No', '* * * 1 * *', 'Base tests for Release Pages.'],
                     ['SMOKE_QA', 'Yes', '5    5,9,15      *     *      *     *', 'Smoke-tests for QA'],
                     ['SMOKE_SEMI', 'Yes', '5   5,9,15      *     *      *     *', 'Smoke-tests for SEMI'],
                     ['SS2_QA', 'Yes', '5    6      *     *      *     *', 'Basic set of selfservice tests in QA'],
                     ['STOREFRONT_SEMI', 'Yes', '5    11      *     *      7     *',
                      'Full set of storefront tests in SEMI'],
                     ['TASKS', 'Yes', '5 */2 * * * *', 'Run any existing tasks stored in tasks table.'],
                     ['T_QUICKCHECK_DD', 'Yes', '5 13 * * 2 *', 'Trial tests for quickcheck on desktop/digital'],
                     ['T_QUICKCHECK_DP', 'Yes', '5 13 * * 2 *', 'Trial quickcheck tests on desktop/plastic'],
                     ['T_QUICKCHECK_MD', 'Yes', '5 13 * * 2 *', 'Trial quickcheck tests on desktop/digital'],
                     ['T_QUICKCHECK_MP', 'Yes', '5 13 * * 2 *', 'Trial quickcheck tests on mobile/plastic'],
                     ['T_QUICKCHECK_S', 'Yes', '5 13 * * 2 *', 'Trial quickcheck tests for Storefront digital'],
                     ['T_RELEASE_PAGES', 'Yes', '5 13 * * 2 *', 'Trial tests for Release Pages.'],
                     ['api_basic_qa', 'Yes', '5    0      *     *      *     *',
                      'Basic set of external-API tests in QA'],
                     ['api_basic_semi', 'Yes', '5    0      *     *      *     *',
                      'Basic set of external-API tests in SEMI'],
                     ['api_risk_basic_qa', 'Yes', '5    0      *     *      *     *',
                      'Basic set of external-API risk tests in QA'],
                     ['api_risk_basic_semi', 'Yes', '5    0      *     *      *     *',
                      'Basic set of external-API risk tests in SEMI'],
                     ['assist_basic_qa', 'Yes', '5   2      *     *      *     *', 'Basic set of assist tests in QA'],
                     ['assist_basic_semi', 'Yes', '5   2      *     *      *     *',
                      'Basic set of assist tests in SEMI'],
                     ['biz_basic_qa', 'Yes', '5   2      *     *      *     *', 'Basic set of biz/bulk tests in QA'],
                     ['biz_basic_semi', 'Yes', '5   2      *     *      *     *',
                      'Basic set of biz/bulk tests in SEMI'],
                     ['capi_basic_qa', 'Yes', '5    1      *     *      *     *', 'Basic set of CAPI tests in QA'],
                     ['capi_basic_semi', 'Yes', '5    1      *     *      *     *', 'Basic set of CAPI tests in SEMI'],
                     ['capi_features_qa', 'Yes', '5    1      *     *      *     *', 'CAPI features tests in QA'],
                     ['capi_features_semi', 'Yes', '5    1      *     *      *     *', 'CAPI features tests in SEMI'],
                     ['clientconfig_basic_qa', 'Yes', '5    4      *     *      *     *',
                      'Full set of clientconfig tests in QA'],
                     ['clientconfig_basic_semi', 'Yes', '5    4      *     *      *     *',
                      'Full set of clientconfig tests in SEMI'],
                     ['data_basic_qa', 'Yes', '5    0      *     *      *     *',
                      'Test data (e.g. gestalt) source in QA'],
                     ['data_basic_semi', 'Yes', '5    0      *     *      *     *',
                      'Test data (e.g. gestalt) source in SEMI'],
                     ['econsumer_basic_qa', 'Yes', '5   4   *     *      *     *',
                      'Basic set of eConsumer tests in QA'],
                     ['econsumer_basic_semi', 'Yes', '5   4   *     *      *     *',
                      'Basic set of eConsumer tests in QA'],
                     ['known_issues_qa', 'Yes', '5    9      *     *      0     *',
                      'Set of tests failing (from low-priority issues) in QA'],
                     ['known_issues_semi', 'Yes', '5    9      *     *      0     *',
                      'Set of tests failing (from low-priority issues) in SEMI'],
                     ['mallfront_basic_qa', 'Yes', '5    5      *     *      *     *',
                      'Basic set of MallFront tests in QA'],
                     ['mallfront_basic_semi', 'No', '5    5      *     *      *     *',
                      'Basic set of MallFront tests in QA'],
                     ['mapi_basic_qa', 'Yes', '5    1      *     *      *     *', 'Basic set of CAPI Mall tests in QA'],
                     ['mapi_basic_semi', 'No', '5    1      *     *      *     *', 'Basic set of Mall tests in SEMI'],
                     ['paypal_basic_qa', 'Yes', '5    5      *     *      *     *', 'Basic set of PayPal tests in QA'],
                     ['paypal_basic_semi', 'Yes', '5    5      *     *      *     *',
                      'Basic set of PayPal tests in SEMI'],
                     ['peg_basic_qa', 'Yes', '5    0      *     *      *     *', 'Basic set of PeG tests in QA'],
                     ['peg_basic_qa_multibrowser_desktop', 'Yes', '5    21      *     *      7     *',
                      'Full set of PeG tests in QA, across multiple browsers'],
                     ['peg_basic_qa_multibrowser_mobile', 'Yes', '5    21      *     *      7     *',
                      'Full set of PeG tests in QA, across multiple browsers'],
                     ['peg_basic_semi', 'Yes', '5    0      *     *      *     *', 'Basic set of PeG tests in SEMI'],
                     ['peg_basic_semi_multibrowser_desktop', 'Yes', '5    21      *     *      7     *',
                      'Full set of PeG tests in SEMI, across multiple browsers on unmanaged brands'],
                     ['peg_basic_semi_multibrowser_mobile', 'Yes', '5    21      *     *      7     *',
                      'Full set of PeG tests in SEMI, across multiple browsers'],
                     ['plastic_basic_qa', 'Yes', '5    0      *     *      *     *',
                      'Basic set of plastic tests across multiple products in QA'],
                     ['plastic_basic_semi', 'Yes', '5    0      *     *      *     *',
                      'Basic set of plastic tests across multiple products in SEMI'],
                     ['program_basic_qa', 'Yes', '5    1      *     *      *     *', 'Basic set of CAPI tests in QA'],
                     ['program_basic_semi', 'Yes', '5    1      *     *      *     *',
                      'Basic set of CAPI tests in SEMI'],
                     ['promo_basic_qa', 'Yes', '5    1      *     *      *     *', 'Basic set of CAPI tests in QA'],
                     ['promo_basic_semi', 'Yes', '5    1      *     *      *     *', 'Basic set of CAPI tests in SEMI'],
                     ['redeem_basic_qa', 'Yes', '5    6      *     *      *     *',
                      'Basic set of redemption tests in QA'],
                     ['redeem_basic_semi', 'Yes', '5    6      *     *      *     *',
                      'Basic set of redemption tests in SEMI'],
                     ['storefront_basic_qa', 'Yes', '5    3      *     *      *     *',
                      'Basic set of Storefront tests in QA'],
                     ['storefront_basic_qa_multibrowser', 'Yes', '5    18      *     *      7     *',
                      'Basic set of Storefront tests in QA across multiple browsers'],
                     ['storefront_basic_semi', 'Yes', '5    3      *     *      *     *',
                      'Basic set of Storefront tests in SEMI'],
                     ['storefront_basic_semi_multibrowser', 'Yes', '5    18      *     *      7     *',
                      'Basic set of Storefront tests in SEMI across multiple browsers'],
                     ['storefront_i18n_qa', 'Yes', '5    4      *     *      *     *',
                      'I18N (i.e. Internationalization)  set of tests for Storefront in SEMI'],
                     ['storefront_i18n_qa_multibrowser', 'Yes', '5    20      *     *      7     *',
                      'Set of I18N (i.e. internationalization) Storefront tests, multiple browsers, in QA'],
                     ['storefront_i18n_semi', 'Yes', '5    4      *     *      *     *',
                      'I18N (i.e. internationalization)  set of tests for Storefront in SEMI'],
                     ['storefront_i18n_semi_multibrowser', 'Yes', '5    20      *     *      7     *',
                      'Set of I18N (i.e. internationalization) Storefront tests in SEMI'],
                     ['storefront_promo_qa', 'Yes', '5    3      *     *      *     *',
                      'Basic set of Storefront promo-tests in QA'],
                     ['storefront_promo_semi', 'Yes', '5    3      *     *      *     *',
                      'Basic set of Storefront promo-tests in SEMI'],
                     ['storefront_regressions_qa', 'Yes', '5    8      *     *      0     *',
                      'Large set of buys across buy_types, currencies and credit cards in QA'],
                     ['storefront_regressions_semi', 'Yes', '5    8      *     *      0     *',
                      'Large set of buys across buy_types, currencies and credit cards in SEMI'],
                     ['storefront_variants_qa', 'Yes', '5    3      *     *      *     *',
                      'Variants (i.e. multi-item buys) set of tests for Storefront in QA'],
                     ['storefront_variants_qa_multibrowser', 'Yes', '5    19      *     *      7     *',
                      'Variant set (i.e. multi-item buys) of Storefront tests, multiple browsers, in QA'],
                     ['storefront_variants_semi', 'Yes', '5    3      *     *      *     *',
                      'Variants (i.e. multi-item buys) set of tests for Storefront in SEMI'],
                     ['storefront_variants_semi_multibrowser', 'Yes', '5    19      *     *      7     *',
                      'Variant set (i.e. multi-item buys) of Storefront tests, multiple browsers, in SEMI'],
                     ['xreport', 'Yes', '5 7 * * * *', 'Generate and email composite report.']]
    return schedule_plus

def prettify_cron_data(cronString):
    # input cron data as a single string, give back a nicely formatted string
    schedline = '|'
    for g in cronString.split():
        # print('{:.>8}'.format(g), end="")
        schedline = schedline + '{: ^6}'.format(g)
    cronString = schedline + '|'
    return cronString


def main():
    print('(load_data) main:')
    print()

    schedule = []

    schedule = load_data(schedule)
    print(schedule)

    width = 3
    for s in schedule:
        # print(s)
        # print(s[2].split())
        cronString=s[2]

        cronString = prettify_cron_data(cronString)

#        print(schedline)
        print(cronString)
        print()


    print()
    print('(load_data) end::')

    return 0
# ----------------------------------------
if __name__ == '__main__':
    result = main()
    sys.exit(0)
